### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:10238/api/admin/books/search?query=자바&queryType=Title
Content-Type: application/json