### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:10236/api/admin/books/search?query=자바&queryType=Title
Content-Type: application/json


###
POST http://localhost:10236/api/admin/books/aladdin/register
Content-Type: application/json

{
  "publisherName": "인피니티북스",
  "productTitle": "Power JAVA - 3판",
  "productIsbn": "9791185578989",
  "productImage": "https://image.aladin.co.kr/product/29009/25/coversum/k452836425_1.jpg",
  "productDescription": "JAVA 입문자들이 쉽고 재미있게 학습할 수 있도록 게임, 인공지능, 그래픽 관련 흥미로운 LAB, Mini Project를 수록하였고 문답식 설명과 다양한 그림 자료를 활용하여 친절하게 설명했다. 최신 버전인 JDK 16 내용을 담았다.",
  "productRegularPrice": 35000,
  "productSalePrice": 35000,
  "contributors": "천인국 (지은이)",
  "productContent": "이 책은",
  "productPackageable": true,
  "productStock": 120
}

###
GET http://localhost:10236/api/category/
