# useSSL=false              : SSL 연결을 사용하지 않도록 설정 (개발 환경에서는 보통 꺼둠)
# serverTimezone=Asia/Seoul : MySQL 서버와 애플리케이션 간의 시간대 일치
# characterEncoding=UTF-8   : 한글 깨짐 방지

# 로컬 유레카 환경 + 개발용 dev DB
server:
  port: 10236

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # Spring Boot에서 SQL 초기화 스크립트 실행 시점을 JPA(Hibernate)의 테이블 생성 이후로 지연시키는 설정
  sql: # 실행할 때 h2 환경의 sample 데이터 넣기
    init:
      mode: always
      data-locations: classpath:sql/h2/sample.sql
      schema-locations: classpath:sql/h2/schema.sql

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 293
  rabbitmq:
    virtual-host: "e2bs_dev"

eureka:
  client:
    fetch-registry: true # Eureka에서 다른 서비스 정보를 받아올지 여부
    register-with-eureka: true # 현재 애플리케이션을 Eureka에 등록할지 여부
    service-url:
      defaultZone: http://admin:1234@localhost:10230/eureka # 로컬 Eureka 서버의 주소
  instance:
    prefer-ip-address: true # 서비스 등록 시 도메인 대신 IP 주소로 등록

order:
  url:
    toss: https://api.tosspayments.com/v1/payments/confirm
  sc: Basic dGVzdF9za19aMWFPd1g3SzhtZTZENURnMnFqbTh5UXh6dk5QOg==