# useSSL=false              : SSL 연결을 사용하지 않도록 설정 (개발 환경에서는 보통 꺼둠)
# serverTimezone=Asia/Seoul : MySQL 서버와 애플리케이션 간의 시간대 일치
# characterEncoding=UTF-8   : 한글 깨짐 방지
spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be9_team2_dev?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: project_be9_team2
    password: "*gzxziN[g9kwl]Ln"