### 상품 좋아요 추가
POST http://localhost:10236/api/products/2/likes
Content-Type: application/json

{
  "memberId": "user6"
}

### 상품 좋아요 취소
DELETE http://localhost:10236/api/products/2/likes?memberId=user6

### 현재 회원이 좋아요 한 상품 페이징 목록
GET http://localhost:10236/api/products/likes?memberId=user6
Content-Type: application/json

### 상품 좋아요 개수 조회
GET http://localhost:10236/api/products/1/likes/counts
Content-Type: application/json


### 회원, 상품 좋아요 여부 확인
GET http://localhost:10236/api/liked?customerId=1&productId=3
Content-Type: application/json

### 회원, 상품 좋아요 단일 조회
GET http://localhost:10236/api/findLiked?customerId=1&productId=3
Content-Type: application/json