### 상품 좋아요 추가
POST http://localhost:10236/api/products/1/likes
Content-Type: application/json

{
  "memberId": "user"
}

### 상품 좋아요 취소
DELETE http://localhost:10236/api/products/1/likes?memberId=user

### 고객 좋아요 페이징 목록 조회
GET http://localhost:10236/api/products/likes?customerId=1
Content-Type: application/json

### 상품 좋아요 개수 조회
GET http://localhost:10236/api/products/1/likes/counts
Content-Type: application/json