### 리뷰 생성
POST http://localhost:10236/api/reviews
Content-Type: application/json

{
  "productId": 1,
  "customerId": 1,
  "reviewContent": "좋아요",
  "reviewGrade": 4,
  "reviewImage": "default.jpg"
}

### 리뷰 수정
PUT http://localhost:10236/api/reviews/1
Content-Type: application/json

{
  "reviewContent": "수정 내용",
  "reviewGrade": 5,
  "reviewImage": "update.jpg"
}

### 상품 리뷰 페이징 목록 조회
GET http://localhost:10236/api/products/1/reviews?page=0&size=5
Content-Type: application/json

### 회원이 작성한 리뷰 페이징 목록 조회
GET http://localhost:10236/api/members/user/reviews?page=0&size=10
Content-Type: application/json

### 상품 리뷰의 전체 평점 및 각 등급의 리뷰 개수 구하기
GET http://localhost:10236/api/products/1/reviews/info
Content-Type: application/json

### 이미지 리뷰 작성
POST http://localhost:10232/api/reviews
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="requestMeta"
Content-Type: application/json

{
  "productId": 1,
  "customerId": null,
  "memberId": "asd",
  "reviewContent": "정말 좋은 제품이었습니다!",
  "reviewGrade": 5
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="reviewImage"; filename="sample.jpg"
Content-Type: image/jpeg